HousesApp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # Base Views
    path('', views.HomeView.as_view(), name='home'),
    path('casas/', views.HousesListView.as_view(), name="house_list"),
    path('casa<int:pk>/', views.HouseDetailView.as_view(), name="house_detail"),
    path('casa<int:pk>/alterar/', views.HouseUpdateView.as_view(), name="house_update"),
    path('casas<int:pk>/eliminar/', views.HouseDeleteView.as_view(), name="house_delete"),
    path('casa<int:house_pk>/upload/', views.create_compartment, name="create_compartment"),
    path('casa/delete_picture/<int:compartment_pk>/', views.delete_compartment, name="delete_compartment"),
    path('casas/submeter/', views.HouseCreateView.as_view(),name="house_create"),
    path('casas/minhas-casas/', views.UserHouseListView.as_view(), name="house_user_houses"),
    path('casa<int:listing_pk>/mostrar-na-lista/', views.toggle_house_visibility, name="house_toggle_visibility")
]

Server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('HousesApp.urls')),
    path('contas/', include('AuthApp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HousesApp/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

YESNO = [
    ("Sim", "Sim"),
    ("Não", "Não"),
]

MAIN_BEDROOM = "Quarto Principal"
BEDROOM = "Quarto"
LIVING_ROOM = "Sala de Estar"
DINING_ROOM = "Sala de Jantar"
KITCHEN = "Cozinha"
BATHROOM = "Quarto de Banho"

ROOMCHOICES = [
    (MAIN_BEDROOM, "Quarto Principal"),
    (BEDROOM, "Quarto"),
    (LIVING_ROOM, "Sala de Estar"),
    (DINING_ROOM, "Sala de Jantar"),
    (KITCHEN, "Cozinha"),
    (BATHROOM, "Quarto de Banho"),
]

class MOZAMBIQUE:
    TETE = "Tete"
    MAPUTO = "Maputo"
    GAZA = "Gaza"
    INHAMBANE = "Inhambane"
    MANICA = "Manica"
    SOFALA = "Sofala"
    ZAMBEZIA = "Zambezia"
    NAMPULA = "Nampula"
    CABO_DELGADO = "Cabo Delgado"
    NIASSA = "Niassa"

    CITY_CHOICES = [
        (TETE,"Tete"),
        (MAPUTO,"Maputo"),
        (GAZA,"Gaza"),
        (INHAMBANE,"Inhambane"),
        (MANICA,"Manica"),
        (SOFALA,"Sofala"),
        (ZAMBEZIA,"Zambezia"),
        (NAMPULA,"Nampula"),
        (CABO_DELGADO,"Cabo Delgado"),
        (NIASSA,"Niassa")
    ]

def validate_non_negative(value):
    if value < 0:
        raise ValidationError('Não são permitidos valores negativos', params={'value' : value})

class HouseListing(models.Model):

    # Dados de Registro
    create_by_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name='houses'
    )

    data_registrada = models.DateField(default=timezone.now)
    mostrar_na_lista = models.BooleanField(default=True)

    # Proprietario
    nome_do_proprietario = models.CharField(max_length=30)
    sobrenome_do_proprietario = models.CharField(max_length=30)

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',message="O número de telefone deve estar no seguinte formato: +999999999999. Deve conter no maximo 15 digitos")
    contacto_principal = models.CharField(max_length=15, validators=[phone_regex])
    contacto_secúndario = models.CharField(max_length=15, validators=[phone_regex],blank=True,null=True)

    # Preçario
    preço = models.FloatField(default=0.0, validators=[validate_non_negative])
    meses_adiantados = models.IntegerField(default=1, validators=[validate_non_negative])

    # Localizaçao
    cidade = models.CharField(max_length=30, choices=MOZAMBIQUE.CITY_CHOICES)
    distrito = models.CharField(max_length=30,blank=True,null=True)
    bairro = models.CharField(max_length=100)

    # Compartimentos
    numero_de_divisoes = models.IntegerField(validators=[validate_non_negative])
    mobiliada = models.CharField(max_length=6, choices=YESNO)
    vedada= models.CharField(max_length=6, choices=YESNO)

    def get_absolute_url(self):
        return reverse('house_detail', kwargs={'pk': self.pk})


class HouseCompartment(models.Model):
    
    house = models.ForeignKey(
        to=HouseListing, 
        on_delete=models.CASCADE, 
        related_name="compartments"
    )

    tipo = models.CharField(max_length=20,choices=ROOMCHOICES)

    foto = models.ImageField(upload_to="images/houses")

HousesApp/forms.py
from django import forms
from .models import HouseListing, HouseCompartment

class HouseListingForm(forms.ModelForm):

    class Meta:
        model = HouseListing
        fields = [
            'nome_do_proprietario',
            'sobrenome_do_proprietario',
            'contacto_principal',
            'contacto_secúndario',
            'preço',
            'meses_adiantados',
            'cidade',
            'distrito',
            'bairro',
            'numero_de_divisoes',
            'mobiliada',
            'vedada'
        ]

        help_texts = {
        	'preço': 'O valor da renda mensal em meticais',
        	'meses_adiantados': 'Quantos meses adiantados o cliente terá que pagar inicialmente',
        	'contacto_principal': 'Usado por clientes para poder contactar o proprietario da casa',
        	'numero_de_divisoes': 'O número total de quartos, salas, cozinhas, etc, disponiveis na casa'
        }

class HouseCompartmentForm(forms.ModelForm):
    class Meta:
        model = HouseCompartment
        fields = [
            'tipo',
            'foto'
        ]

HousesApp/views.py
from .models import HouseListing, HouseCompartment
from .forms import HouseListingForm, HouseCompartmentForm
from .mixins import UserOwnsHouseMixin

from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import (
    TemplateView, 
    ListView, 
    DetailView, 
    CreateView, 
    UpdateView, 
    DeleteView
)

# Create your views here.
class HomeView(TemplateView):
    template_name = "HousesApp/houses_home.html"

class HousesListView(ListView):
    model = HouseListing
    paginate_by = 3
    context_object_name = "houses"
    template_name = "HousesApp/houses_list.html"

    def get_queryset(self):
        listings = HouseListing.objects.filter(mostrar_na_lista=True)
        
        if self.request.GET.__contains__('cidade'):
            cidade = self.request.GET['cidade']
            if cidade != "all":
               listings = listings.filter(cidade__icontains=cidade)

        if self.request.GET.__contains__('distrito'):
            distrito = self.request.GET['distrito']
            
            if distrito != "":
                listings = listings.filter(distrito__icontains=distrito)

        if self.request.GET.__contains__('price_range'):
            price_range = self.request.GET['price_range']

            if price_range != "all":
                if price_range == "low":
                    min_price = 500
                    max_price = 5000

                if price_range == "medium":
                    min_price = 5000
                    max_price = 15000

                if price_range == "high":
                    min_price = 15000
                    max_price = 25000

                listings = listings.filter(preço__range=(min_price,max_price))

        if self.request.GET.__contains__('room_count'):
            room_count = self.request.GET['room_count']
            try:
                room_count = int(room_count)

                if room_count > 0:
                    listings = listings.filter(numero_de_divisoes=room_count)
                
            except Exception as e:
                print("Room count not valid")

        return listings

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.GET.__contains__('cidade'):
            context['cidade'] = self.request.GET['cidade']

        if self.request.GET.__contains__('distrito'):
            context['distrito'] = self.request.GET['distrito']

        if self.request.GET.__contains__('price_range'):
            context['price_range'] = self.request.GET['price_range']

        if self.request.GET.__contains__('room_count'):
            context['room_count'] = self.request.GET['room_count']

        return context

class HouseDetailView(DetailView):
    model = HouseListing
    context_object_name = "house"
    template_name = "HousesApp/houses_details.html"

class HouseCreateView(LoginRequiredMixin,CreateView):
    form_class = HouseListingForm
    template_name = "HousesApp/houses_create.html"
    permission_denied_message = 'Login is required'

    def form_valid(self,form):
        form.instance.create_by_user = self.request.user
        return super().form_valid(form)

class HouseUpdateView(LoginRequiredMixin,UserOwnsHouseMixin,UpdateView):
    model = HouseListing
    form_class = HouseListingForm
    template_name = "HousesApp/houses_update.html"
    context_object_name = "house"
    permission_denied_message = 'Login is required'

class HouseDeleteView(LoginRequiredMixin,UserOwnsHouseMixin,DeleteView):
    model = HouseListing
    template_name = "HousesApp/houses_confirm_delete.html"
    context_object_name = "house"

    def get_success_url(self):
        return reverse('house_user_houses')

class UserHouseListView(LoginRequiredMixin,ListView):
    model = HouseListing
    template_name = "HousesApp/houses_user_houses.html"
    context_object_name = "houses"

    def get_queryset(self):
        return HouseListing.objects.filter(create_by_user=self.request.user)


def create_compartment(request,house_pk):

    house = get_object_or_404(HouseListing,pk=house_pk)

    if request.user != house.create_by_user:
        return redirect(house)

    form = HouseCompartmentForm()

    if request.method == 'POST':
        
        form = HouseCompartmentForm(request.POST,request.FILES)

        if form.is_valid():
            form.instance.house = house
            form.save()
            return redirect("create_compartment", house_pk=house_pk)

    return render(request,'HousesApp/upload_image.html',context={'house' : house, 'form' : form})

def delete_compartment(request, compartment_pk):
    compartment = get_object_or_404(HouseCompartment, pk=compartment_pk)

    if request.user != compartment.house.create_by_user:
        return redirect("home")

    compartment.delete()
    return redirect("create_compartment", house_pk=compartment.house.pk)

def toggle_house_visibility(request,house_pk):
    house = get_object_or_404(HouseListing,pk=house_pk)

    if request.user != house.create_by_user:
        return redirect(house)

    house.mostrar_na_lista = not house.mostrar_na_lista
    house.save()

    return redirect(house)

HousesApp/templates/HousesApp/houses_confirm_delete.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container">
	<form  action="{% url 'house_delete' house.pk %}" method="post">
		{% csrf_token %}
		
		<h4>Tem Certeza que deseja eliminar esta casa?</h4>
		<p>Nota:Essa acção é irreversivel</p>
		<input type="submit" name="submit" value="Confirmar" class="btn btn-danger">
		<a href="{% url 'house_detail' house.pk %}" class="btn btn-secondary">Cancelar</a>
	</form>
</div>
{% endblock content %}

HousesApp/templates/HousesApp/houses_create.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <form action="{% url 'house_create' %}" method="post"> 
            {% csrf_token %}
            <div class="row form-title">
                <div class="col-md-11">
                    <h3 class="form-title">Dados do Proprietário</h3>
                </div>
                <div class="col-md-1">
                    <img src="{% static 'img/icons/proprietario.png'%}" alt="">
                </div>
            </div>
            <div class="row mt-3">
                <div class="form-group col-md-6">
                    {{form.nome_do_proprietario | as_crispy_field }}
                </div>
                <div class="form-group col-md-6">
                    {{form.sobrenome_do_proprietario | as_crispy_field }}
                </div>
            </div>
            <div class="row mt-2">
                <div class="form-group col-md-6">
                    {{form.contacto_principal | as_crispy_field }}
                </div>
                <div class="form-group col-md-6">
                    {{form.contacto_secúndario | as_crispy_field }}
                </div>
            </div>

            <div class="row form-title mt-4">
                <div class="col-md-11">
                    <h3 class="form-title">Dados da Propriedade </h3>
                </div>
                <div class="col-md-1">
                    <img src="{% static 'img/icons/propriedade.png'%}" alt="">
                </div>
            </div>
            
            <div class="row mt-2">
                <div class="form-group col-md-6">
                    {{form.preço | as_crispy_field }}
                </div>
                <div class="form-group col-md-6">
                    {{form.meses_adiantados | as_crispy_field }}
                </div>
            </div>

            <h5 class="mt-3">Localização</h5>
            <div class="row">
                <div class="form-group col-md-4">
                    {{form.cidade | as_crispy_field }}
                </div>

                <div class="form-group col-md-4">
                    {{form.distrito | as_crispy_field }}
                </div>
                <div class="form-group col-md-4">
                    {{form.bairro | as_crispy_field }}
                </div>
            </div>

            <h5 class="mt-3">Caracteristicas</h5>
            <div class="row">
                <div class="form-group col-md-4">
                    {{form.numero_de_divisoes | as_crispy_field }}
                </div>

                <div class="form-group col-md-4">
                    <p><b>Tem Mobilia?</b></p>
                    <label for="mobiliada">Sim</label>
                    <input type="radio" value="Sim" name="mobiliada">
                    <label for="mobiliada">Não</label>
                    <input type="radio" value="Não" name="mobiliada">
                </div>

                <div class="form-group col-md-4">
                    <p><b>Esta Vedada?</b></p>
                    <label for="vedada">Sim</label>
                    <input type="radio" value="Sim" name="vedada">
                    <label for="vedada">Não</label>
                    <input type="radio" value="Não" name="vedada">
                </div>
            </div>   

            <div class="row mt-4 mb-5">
                <div class="col-md-4 mt-4">
                    <button class="btn btn-primary col-md-12" type="submit">Submeter</button>
                </div>
                <div class="col-md-4">
                    
                </div>
                <div class="col-md-4 mt-4">
                    <a href="{% url 'home' %}" class="btn btn-danger col-md-12">Cancelar</a>
                </div>
            </div>    
        </form>    
    </div>
{% endblock content %}

HousesApp/templates/HousesApp/houses_details.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            
            <div class="col-md-1">
            </div>

            <div class="col-md-10">

                <div class="carousel slide" id="carouselSite" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <!--A Imagem sendo adicionada-->
                        <div class="carousel-item active">
                            <img 
                            	src="{% static 'img/house_preview_1_detail.png' %}" 
                            	class="img-fluid d-block imgSlide"
                                width="1000" 
                                height="600"
                            >
                            <div class="carousel-caption d-md-block destaque" >
                                <!--O Texto que acompanha a imagem-->
                                <div class="slideInfo">
                                    <h3 class="h3Slide">
                                    Casa com {{house.numero_de_divisoes}} divisões
                                	</h3>
                                </div>
                            </div>
                        </div>
                        {% for compartimento in house.compartments.all %}
                        <div class="carousel-item">
                            <img 
                                src="{{compartimento.foto.url}}" 
                                class="img-fluid d-block imgSlide" 
                                width="1000" 
                                height="600" 
                            >
                            <div class="carousel-caption d-md-block destaque" >
                                <!--O Texto que acompanha a imagem-->
                                <div class="slideInfo">
                                    <h3 class="h3Slide">
                                        {{compartimento.tipo}}
                                    </h3>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="carousel-item">
                            <img 
                            	src="{% static 'img/house_preview_2_detail.png' %}" 
                            	class="img-fluid d-block imgSlide"
                                width="1000" 
                                height="600"
                            >

                            <div class="carousel-caption d-md-block" >
                                <!--O Texto que acompanha a imagem-->
                                <div class="slideInfo">
                                   	<h3 class="h3Slide">
                                        Renda {{house.preço}} MZN
                                    </h3>
                                    <h5 class="h4Slide">
                                        Ligue: {{house.contacto_principal}}
                                        {% if house.contacto_secúndario %}
                                             ou {{house.contacto_secúndario}}
                                        {% endif %}
                                    </h5>
                                </div>
                            </div>
                        </div>

                        <div class="carousel-control">
                            <a 
                                href="#carouselSite" 
                                class="carousel-control-prev" 
                                role="button"
                                data-bs-target=""  
                                data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon"></span>
                                    <span class="sr-only">Anterior</span>
                            </a>

                            <a 
                                href="#carouselSite" 
                                class="carousel-control-next" 
                                role="button"  
                                data-bs-slide="next">
                                    <span class="sr-only">Proximo</span>
                                    <span class="carousel-control-next-icon"></span>
                            </a>
                        </div>

                    </div>
            </div>

            <a 
                class="mt-2 mb-2    " 
                data-bs-toggle="collapse" 
                href="#collapseExample" 
                role="button" 
                aria-expanded="false" 
                aria-controls="collapseExample">
                    <h3>Detalhes</h3>
            </a>

            <div class="collapse" style="margin-left: 20px;" id="collapseExample">
                <div class="row">
                    <div class="col-md-8">
                        <table class="table table-striped">
                            <tr>
                                <td><p class="descricao">Nome do Proprietário: </p></td>
                                <td><p class="descricao">{{house.nome_do_proprietario}} {{house.sobrenome_do_proprietario}}</p></td>
                            </tr>
                            <tr>
                                <td><p class="descricao">Contacto:</p></td>
                                <td>
                                    <p class="descricao">
                                        {{house.contacto_principal}}
                                        {% if house.contacto_secúndario %}
                                            ou {{house.contacto_secúndario}}
                                        {% endif %}
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td><p class="descricao strong">Localização da Residência:</p></td>
                                <td><p class="descricao">{{house.bairro}}, {% if house.distrito%}{{house.distrito}} - {% endif %}{{house.cidade}}</p></td>
                            </tr>
                            <tr>
                                <td><p class="descricao">Número de Divisões:</p></td>
                                <td><p class="descricao">{{house.numero_de_divisoes}}</p></td>
                            </tr>
                            <tr>
                                <td><p class="descricao">Vedada:</p></td>
                                <td><p class="descricao">{{house.vedada}}</p></td>
                            </tr>
                            <tr>
                                <td><p class="descricao">Mobiliada:</p></td>
                                <td><p class="descricao">{{house.mobiliada}}</p></td>
                            </tr>
                            <tr>
                                <td><p class="descricao">Renda:</p></td>
                                <td><p class="descricao">{{house.preço}} Mts</p></td>
                            </tr>
                            <tr>
                                <td><p class="descricao">Entrada:</p></td>
                                <td><p class="descricao">{{house.meses_adiantados}} Meses</p></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>

            <a href="{% url 'house_list' %}" class="btn btn-secondary">Voltar</a>

    </div>
{% endblock content %}

HousesApp/templates/HousesApp/houses_home.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
<style type="text/css">
    body{
        background-image: url({% static 'img/bg2.png' %});
        background-repeat: no-repeat;
        background-size: cover;
    }

    #navigation_bar{
        background: black;
        background-color: transparent!important;
    }

    @media (max-width:576px){

        #navigation_bar{
            background-color: #eee!important;
            color: white;
        }
    }
</style>
{% endblock css%}

{% block content %}
<div class="container">
    <h1>Encontre aqui</h1>
    <h3 id="slogan">a sua casa dos sonhos</h3>
    <p class="info col-md-4">
        A <B>RentAHouse</B> é um serviço de arrendamento de imóveis nas cidades de Tete e Moatize, assim
        como na província de Tete. Encontre aqui a casa dos seus sonhos, para criar os seus filhos,
        sua família, ou por outras, para alojar os seus funcionários.
    </p>
    <br>
    <a  href="{% url 'house_list'%}" class="btn btn-success col-md-2 userButton"> Arrendar Casa </a>
    <a href="{% url 'house_create' %}" class="btn btn-outline-success col-md-2 userButton" >Submeter Casa</a>
</div>

</div>  
<div class="info"> 
    
</div> 

{% endblock content %}

HousesApp/templates/HousesApp/houses_list.html
{% extends 'layout.html' %}

{% load static %}

{% block css %}
{% endblock css %}

{% block content %}

    <div class="container">

        <h1>Encontre Casas {% if cidade and cidade != "all" %} em {{cidade}} {% endif %}</h1>

        <div class="col-md-2">
            <p>
                <a 
                    data-bs-toggle="collapse" 
                    href="#collapseExample" 
                    role="button" 
                    aria-expanded="false" 
                    aria-controls="collapseExample">
                        Filtrar
                </a>
            </p>
        </div>    
        
        <form action="{% url 'house_list' %}" method="get" class="collapse mb-4" id="collapseExample">
            <div class="row">
                <div class="col-md-3">
                    <label for="id_cidade" class="form-check-label">Provincia:</label>
                    <select class="form-select" name="cidade" id="id_cidade">
                        <option value="all">(Qualquer)</option>
                        <option value="Tete" {% if cidade == "Tete" %}selected=true{% endif %}>Tete</option>
                        <option value="Maputo" {% if cidade == "Maputo" %}selected=true{% endif %}>Maputo</option>
                        <option value="Gaza"{% if cidade == "Gaza" %}selected=true{% endif %}>Gaza</option>
                        <option value="Inhambane" {% if cidade == "Inhambane" %}selected=true{% endif %}>Inhambane</option>
                        <option value="Manica" {% if cidade == "Manica" %}selected=true{% endif %}>Manica</option>
                        <option value="Sofala" {% if cidade == "Sofala" %}selected=true{% endif %}>Sofala</option>
                        <option value="Zambezia" {% if cidade == "Zambezia" %}selected=true{% endif %}>Zambezia</option>
                        <option value="Nampula" {% if cidade == "Nampula" %}selected=true{% endif %}>Nampula</option>
                        <option value="Cabo Delgado" {% if cidade == "Cabo Delgado" %}selected=true{% endif %}>Cabo Delgado</option>
                        <option value="Niassa" {% if cidade == "Niassa" %}selected=true{% endif %}>Niassa</option>
                    </select>
                </div>

                <div class="col-md-3">
                    <label for="id_distrito" class="form-check-label">Distrito:</label>
                    <input type="text" value="{{distrito}}" name="distrito" id="id_distrito" class="form-control" placeholder="Qualquer">
                </div>
                
                <div class="col-md-3">
                    <label for="id_price_range" class="form-check-label">Preço:</label>
                    <select class="form-select" name="price_range" id="id_price_range">
                        <option value="all"><b>(Qualquer)</b></option>
                        <option value="low" {% if price_range == "low" %}selected=true{% endif%}>500 à 5.000 meticais</option>
                        <option value="medium" {% if price_range == "medium" %}selected=true{% endif%}>5.000 à 15.000 meticais</option>
                        <option value="high" {% if price_range == "high" %}selected=true{% endif%}>15.000 à 25.000 meticais</option>
                    </select>
                </div>

                <div class="col-md-3">
                    <label for="id_room_count">Número de Quartos</label>
                    <input type="number" value="{{room_count}}" name="room_count" id="id_room_count" class="form-control">
                </div>

                <div class="row mt-2">
                    <div class="col-md-10">
                        <button class="btn btn-sm btn-primary" type="submit">Actualizar</button>
                    </div>  
                </div>
                
            </div>
          </form>

        {% if paginator.count <= 0 %}
            <div class="text-center">
                <h1 class="text-info">Nenhuma Casa Encontrada</h1>
                {% if cidade and cidade != "all" or distrito or price_range or room_count %}
                <h3><a href="{% url 'house_list' %}">Desfazer Filtros</a></h3>
                {% else %}
                <h3><a href="{% url 'house_create' %}">Registrar Casa</a></h3>
                {% endif %}
            </div>
        {% endif %}     
        <div class="row">
            {% for house in page_obj %}
            <div class="col-md-4 mb-4">
                <div class="card" style=" min-height: 370px;">
                    <img src="{% static 'img/house_preview_2.jpg' %}" alt="">
                    <div class="card-body">
                        <h4 class="card-title"> {{ house.bairro}}, {{house.cidade}}{% if house.distrito %}/{{house.distrito}}{% endif %}</h4>
                        <h5 class="card-subtitle mb-2 text-muted proprietario">Proprietário: {{house.nome_do_proprietario}} {{house.sobrenome_do_proprietario}}</h5>
                    </div>

                    <div class="card-footer">
                        <h5 class="card-subtitle mb-2 text-muted proprietario">Renda: <b class="text-info">{{house.preço}} MZN</b> por mês </h5>
                        <a href="{% url 'house_detail' house.pk %}" class="btn btn-sm btn-primary">Ver mais</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        {% if paginator.count > 0 %}
        <div class="pagination text-center row">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; primeira</a>
                    <a href="?page={{ page_obj.previous_page_number }}">voltar</a>
                {% endif %}

                <span class="current">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">próxima</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
{% endblock content %}